import { derived, writable } from 'svelte/store';

const storageKeys = {
  language: 'mothx.webui.language',
  themeMode: 'mothx.webui.themeMode'
};

const dictionaries = {
  zh: {
    'app.name': 'MothX',
    'app.local': '本地运行',
    'app.unknownPage': '未知的页面',
    'common.add': '添加',
    'common.clear': '清空',
    'common.close': '关闭',
    'common.completed': '完成',
    'common.connected': '已连接',
    'common.count': '{count} 个',
    'common.create': '创建',
    'common.delete': '删除',
    'common.disabled': '关闭',
    'common.disabledState': '已禁用',
    'common.disconnected': '未连接',
    'common.enable': '启用',
    'common.disable': '停用',
    'common.enabled': '开启',
    'common.failed': '失败',
    'common.first': '第一页',
    'common.idle': '空闲',
    'common.items': '共 {count} 项',
    'common.last': '最后一页',
    'common.loading': '加载中...',
    'common.next': '下次 {time}',
    'common.nextPage': '下一页',
    'common.no': '否',
    'common.open': '打开',
    'common.pending': '待处理',
    'common.previous': '上一页',
    'common.refresh': '刷新',
    'common.remove': '移除',
    'common.running': '运行中',
    'common.save': '保存',
    'common.stop': '停止',
    'common.times': '{count} 次',
    'common.uninitialized': '未初始化',
    'common.yes': '是',
    'nav.newChat': '新对话',
    'nav.sessions': '历史对话',
    'nav.skills': '技能市场',
    'nav.stats': '统计数据',
    'nav.cron': '定时任务',
    'nav.channels': '通道',
    'nav.logs': '日志',
    'nav.settings': '设置',
    'sidebar.search': '搜索会话...',
    'sidebar.history': '历史对话',
    'sidebar.all': '全部',
    'sidebar.defaultSession': '默认会话',
    'sidebar.noHistory': '暂无历史',
    'sidebar.noMatches': '未匹配到会话',
    'sidebar.stats': '统计数据',
    'sidebar.stats.requests': '请求',
    'sidebar.stats.tokens': 'Token',
    'sidebar.stats.input': '输入',
    'sidebar.stats.output': '输出',
    'channels.title': '消息通道',
    'channels.name': '名称',
    'channels.enabled': '启用',
    'channels.status': '状态',
    'channels.empty': '无通道',
    'settings.channels.saved': '通道配置已保存。',
    'settings.channels.configure': '配置',
    'settings.channels.websocketHint': '本地 WebSocket 通道，启用后立即挂载 /ws。',
    'settings.channels.websocketToggle': '启用 WebSocket 通道',
    'settings.channels.websocketEnabled': 'WebSocket 通道已启用。',
    'settings.channels.websocketDisabled': 'WebSocket 通道已停用。',
    'settings.channels.feishuHint': '飞书长连接需要 App ID 和 App Secret。',
    'settings.channels.feishuConfig': '配置飞书',
    'settings.channels.feishuConfigHint': '保存后会写入 serve.json；启用状态会立即同步到运行时。',
    'settings.channels.feishuKeyRequired': '启用飞书需要填写 App ID 和 App Secret。',
    'settings.channels.feishuSaved': '飞书配置已保存。',
    'settings.channels.wechatHint': '微信需要扫码登录；扫码确认成功后会自动启用。',
    'settings.channels.wechatSaved': '微信配置已保存。',
    'settings.channels.wechatDisabled': '微信通道已停用。',
    'settings.channels.wechatEnabled': '微信扫码成功，通道已启用。',
    'settings.channels.wechatScanEnable': '扫码启用',
    'settings.channels.wechatRelogin': '重新扫码',
    'settings.channels.wechatLogin': '微信扫码登录',
    'settings.channels.wechatLoginHint': '点击新标签打开二维码，使用微信扫描并在手机上确认。',
    'settings.channels.wechatOpenQrHint': '二维码已生成，请点击下方按钮在新标签页打开。',
    'settings.channels.wechatNoQr': '二维码尚未生成。',
    'settings.channels.refreshQr': '刷新二维码',
    'settings.channels.openQrTab': '新标签打开二维码',
    'settings.channels.popupBlocked': '浏览器拦截了新标签页，请点击“新标签打开二维码”。',
    'settings.channels.wechatState.idle': '未登录',
    'settings.channels.wechatState.starting': '生成二维码',
    'settings.channels.wechatState.pending': '等待扫码',
    'settings.channels.wechatState.scanned': '已扫码，等待确认',
    'settings.channels.wechatState.confirmed': '已登录',
    'settings.channels.wechatState.expired': '二维码已过期',
    'settings.channels.wechatState.error': '登录失败',
    'settings.channels.wechatState.cancelled': '已取消',
    'logs.filter': '过滤日志内容',
    'logs.connect': '连接',
    'logs.disconnect': '断开',
    'logs.empty': '暂无日志',
    'sessions.deleted': '会话 {id} 已删除',
    'sessions.filter': '过滤会话（ID / 工作目录 / 标题）',
    'sessions.session': '会话',
    'sessions.workDir': '工作目录',
    'sessions.status': '状态',
    'sessions.messageCount': '消息数',
    'sessions.active': '运行中',
    'sessions.history': '历史',
    'sessions.empty': '没有可显示的会话',
    'sessions.pageRange': '{start}-{end} / {total}',
    'stats.range': '统计范围',
    'stats.range.today': '今天',
    'stats.range.week': '最近 7 天',
    'stats.range.month': '最近 30 天',
    'stats.range.all': '全部',
    'stats.loadFailed': '加载统计数据失败',
    'stats.requests': '请求数',
    'stats.totalTokens': '总 Token',
    'stats.inputTokens': '输入 Token',
    'stats.outputTokens': '输出 Token',
    'stats.trend': '使用趋势',
    'stats.providers': 'Provider 排行',
    'stats.models': '模型排行',
    'stats.recent': '最近请求',
    'stats.empty': '暂无统计数据',
    'stats.time': '时间',
    'stats.model': '模型',
    'stats.provider': 'Provider',
    'stats.input': '输入',
    'stats.output': '输出',
    'stats.duration': '耗时',
    'stats.pageInfo': '{page} / {total}',
    'cron.created': '已创建定时任务',
    'cron.deleted': '已删除任务 {id}',
    'cron.newTask': '新建任务',
    'cron.name': '名称',
    'cron.namePlaceholder': '每日总结',
    'cron.schedule': '调度表达式',
    'cron.schedulePlaceholder': '@daily 或 0 9 * * *',
    'cron.mode': '模式',
    'cron.oneshot': '一次性执行',
    'cron.promptPlaceholder': '要执行的指令...',
    'cron.list': '任务列表',
    'cron.empty': '暂无任务',
    'dirBrowser.title': '选择工作目录',
    'dirBrowser.up': '上级',
    'dirBrowser.loading': '加载中...',
    'dirBrowser.empty': '无子目录',
    'dirBrowser.cancel': '取消',
    'dirBrowser.select': '选择此目录',
    'prefs.language': '语言',
    'prefs.theme': '主题',
    'prefs.zh': '中',
    'prefs.en': 'EN',
    'prefs.light': '日间',
    'prefs.dark': '夜间',
    'prefs.auto': '自动',
    'prefs.preferences': '偏好设置',
    'topbar.chat.subtitle': 'AI 生成可能有误，请核实',
    'topbar.sessions.subtitle': '管理所有会话历史',
    'topbar.skills.subtitle': '浏览、安装并激活 SkillHub / ClawHub 技能',
    'topbar.stats.subtitle': '查看请求、Token、模型和 Provider 使用情况',
    'topbar.cron.subtitle': '调度自动运行的任务',
    'topbar.channels.subtitle': '外部消息通道状态',
    'topbar.logs.subtitle': '实时日志流',
    'topbar.settings.subtitle': 'Serve / 供应商 / App / Memory 配置',
    'topbar.openLogs': '开启日志',
    'topbar.closeLogs': '关闭日志',
    'topbar.refresh': '刷新',
    'skills.market': '市场',
    'skills.view': '视图',
    'skills.browse': '浏览',
    'skills.search': '搜索',
    'skills.official': '官方',
    'skills.searchPlaceholder': '搜索技能名称或用途...',
    'skills.scope': '安装范围',
    'skills.scope.project': '当前项目',
    'skills.scope.global': '全局',
    'skills.category': '分类',
    'skills.allCategories': '全部分类',
    'skills.sort': '排序',
    'skills.downloads': '下载量',
    'skills.installs': '安装量',
    'skills.updatedAt': '更新时间',
    'skills.results': '技能列表',
    'skills.empty': '没有匹配的技能',
    'skills.page': '第 {page} 页',
    'skills.detail': '技能详情',
    'skills.notAvailable': '暂无',
    'skills.noDescription': '暂无描述',
    'skills.install': '安装',
    'skills.installActivate': '安装并激活',
    'skills.update': '更新',
    'skills.activate': '激活',
    'skills.active': '当前会话已激活',
    'skills.source': '来源',
    'skills.downloadSources': '下载来源',
    'skills.fallback': '回退',
    'skills.files': '文件',
    'skills.security': '安全报告',
    'skills.evaluation': '评测详情',
    'skills.select': '从左侧选择一个技能查看详情',
    'skills.installed': '已安装 {name}',
    'skills.updated': '已更新 {name}',
    'skills.activated': '已在当前会话激活 {name}',
    'settings.tabs.overview': '概览',
    'settings.tabs.serve': 'Serve 配置',
    'settings.tabs.workdir': '工作目录',
    'settings.tabs.providers': '供应商设置',
    'settings.tabs.app': '应用设置',
    'settings.tabs.memory': 'Memory',
    'settings.tabs.features': '功能开关',
    'settings.tabs.channels': '通道',
    'settings.tabs.logs': '日志',
    'settings.unknown': '未知的设置分组',
    'settings.overview.serve.desc': 'HTTP 监听、通道、WebUI 静态目录等运行时配置。',
    'settings.overview.providers.desc': '默认 Provider、默认模型、模型参数和所有供应商配置。',
    'settings.overview.app.desc': '模式、上下文压缩、工具状态和审批策略等应用层参数。',
    'settings.overview.memory.desc': '长期记忆 memory.md 的启用与内容编辑。',
    'settings.overview.channels.desc': '配置 WebSocket、飞书和微信扫码通道。',
    'settings.overview.features.desc': '开关 API、WebSocket、Cron、Memory 等模块。',
    'settings.runtime.title': '运行时信息',
    'settings.runtime.version': '版本',
    'settings.runtime.listen': '监听',
    'settings.runtime.sessions': '会话总数',
    'settings.runtime.api': 'OpenAI API',
    'settings.features.hint': '只读展示。修改请在「Serve 配置」或「应用设置」中调整。',
    'settings.features.feature': '功能',
    'settings.features.status': '状态',
    'settings.features.description': '说明',
    'settings.features.api.label': 'OpenAI 兼容 API',
    'settings.features.api.desc': '开启后可通过 /v1/chat/completions 调用。',
    'settings.features.webUI.label': 'Web UI',
    'settings.features.webUI.desc': '当前界面本身，来自 Serve 静态资源目录。',
    'settings.features.websocket.label': 'WebSocket 日志',
    'settings.features.websocket.desc': '/ws/logs 实时日志推送。',
    'settings.features.cron.label': 'Cron 定时任务',
    'settings.features.cron.desc': '基于本地任务清单的调度器。',
    'settings.features.memory.label': 'Memory',
    'settings.features.memory.desc': 'memory.md 长期记忆。',
    'settings.features.multiAgent.label': '多 Agent',
    'settings.features.multiAgent.desc': '允许 spawn / send / destroy 子 Agent 工具。',
    'settings.memory.saved': 'Memory 已保存。',
    'settings.memory.notInitialized': '尚未初始化',
    'settings.providers.saved': '供应商设置已保存。',
    'settings.providers.hint': '默认厂商/模型、全局模型参数和所有 Provider/Model 配置。',
    'settings.providers.sections.defaults': '默认模型',
    'settings.providers.defaultsHint': '控制默认 Provider、默认模型、默认思考等级和全局 Token 上限。',
    'settings.app.saved': '应用设置已保存。',
    'settings.app.hint': '/api/settings - Approval / Context / Tools 等',
    'settings.app.parseError': '当前 settings JSON 解析失败：{error}',
    'settings.app.sections.defaults': '默认行为',
    'settings.app.defaultsHint': '运行模式、目录和启动时默认值。',
    'settings.app.defaultProvider': '默认 Provider',
    'settings.app.defaultModel': '默认模型',
    'settings.app.defaultMode': '默认模式',
    'settings.app.thinking': '默认思考等级',
    'settings.app.maxContextTokens': '最大上下文 Token',
    'settings.app.maxOutputTokens': '最大输出 Token',
    'settings.app.skillsDir': 'Skills 目录',
    'settings.app.sessionDir': 'Session 目录',
    'settings.app.shellPath': 'Shell 路径',
    'settings.app.shellPrefix': 'Shell 命令前缀',
    'settings.app.enablePlanTool': 'Plan 工具',
    'settings.app.updateCheck': '更新检查',
    'settings.app.sections.context': '上下文与压缩',
    'settings.app.contextHint': '上下文文件、压缩窗口和空闲压缩策略。',
    'settings.app.contextFiles': '启用上下文文件',
    'settings.app.compaction': '启用上下文压缩',
    'settings.app.reserveTokens': '保留 Token',
    'settings.app.keepRecentTokens': '保留最近 Token',
    'settings.app.tokenizer': 'Tokenizer',
    'settings.app.tokenizerModel': 'Tokenizer 模型',
    'settings.app.idleCompression': '空闲压缩',
    'settings.app.idleTimeout': '空闲超时（秒）',
    'settings.app.idleMinTokens': '空闲压缩最小 Token',
    'settings.app.compactionTemplate': '压缩模板',
    'settings.app.extraFiles': '额外上下文文件',
    'settings.app.sections.tools': '工具与状态',
    'settings.app.toolsHint': 'Web Search、重试和状态栏行为。',
    'settings.app.webSearch': 'Web Search',
    'settings.app.webSearchProvider': 'Search Provider',
    'settings.app.webSearchType': 'Provider 类型',
    'settings.app.webSearchModel': 'Search 模型',
    'settings.app.retry': '启用重试',
    'settings.app.maxRetries': '最大重试次数',
    'settings.app.baseDelay': '基础延迟（毫秒）',
    'settings.app.statusLine': '启用状态栏',
    'settings.app.statusLineType': '状态栏类型',
    'settings.app.statusLineCommand': '状态栏命令',
    'settings.app.statusLineTimeout': '状态栏超时（毫秒）',
    'settings.app.statusLineFallback': '状态栏 fallback',
    'settings.app.sections.safety': '安全与审批',
    'settings.app.safetyHint': 'Sandbox 路径边界、网络和审批规则。',
    'settings.app.sandbox': '启用 Sandbox',
    'settings.app.allowNetwork': '允许网络',
    'settings.app.sandboxLevel': 'Sandbox 等级',
    'settings.app.bwrapPath': 'bwrap 路径',
    'settings.app.tmpSize': '临时目录大小',
    'settings.app.confirmBeforeWrite': '写入前确认',
    'settings.app.allowedRead': '允许读取路径',
    'settings.app.allowedWrite': '允许写入路径',
    'settings.app.deniedPaths': '禁止路径',
    'settings.app.passEnv': '透传环境变量',
    'settings.app.bashWhitelist': 'Bash 自动批准前缀',
    'settings.app.bashBlacklist': 'Bash 强制审批前缀',
    'settings.app.sections.providers': 'Providers',
    'settings.app.providersHint': '共 {count} 个 provider；高级字段会保留在 JSON 中。',
    'settings.app.noProviders': '暂无 Provider 配置',
    'settings.app.unnamedProvider': '未命名 Provider',
    'settings.app.providerID': 'Provider ID',
    'settings.app.providerVendor': 'Vendor',
    'settings.app.providerAPI': 'API 类型',
    'settings.app.providerThinkingFormat': 'Thinking 格式',
    'settings.app.providerBaseURL': 'Base URL',
    'settings.app.providerAPIKey': 'API Key',
    'settings.app.httpProxy': 'HTTP Proxy',
    'settings.app.forceHTTP11': '强制 HTTP/1.1',
    'settings.app.cacheControl': 'Cache Control',
    'settings.app.reasoningSummary': 'Reasoning Summary',
    'settings.app.promptCacheKey': 'Prompt Cache Key',
    'settings.app.promptCacheRetention': 'Prompt Cache Retention',
    'settings.app.addHeader': '添加 Header',
    'settings.app.addModel': '添加模型',
    'settings.app.headers': 'Headers',
    'settings.app.models': '模型列表',
    'settings.app.modelID': '模型 ID',
    'settings.app.modelName': '显示名',
    'settings.app.modelContext': '上下文',
    'settings.app.modelMaxTokens': '最大输出',
    'settings.app.modelTemperature': '温度',
    'settings.app.modelTopP': 'Top P',
    'settings.app.modelInput': '输入',
    'settings.app.modelReasoning': '推理',
    'settings.app.modelActions': '操作',
    'settings.app.advancedJson': '高级 JSON',
    'settings.app.advancedJsonHint': '保留未图形化字段；通常不需要直接编辑。',
    'settings.serve.saved': 'Serve 配置已保存。监听或通道变更需要重启生效。',
    'settings.serve.sections.runtime': '运行入口',
    'settings.serve.runtimeHint': '监听、默认模型和请求限制。监听地址变更通常需要重启。',
    'settings.serve.listen': '监听地址',
    'settings.serve.webuiDir': 'Web UI 目录',
    'settings.serve.provider': '默认 Provider',
    'settings.serve.model': '默认模型',
    'settings.serve.defaultMode': '默认模式',
    'settings.serve.thinking': '默认思考等级',
    'settings.serve.timeout': '请求超时（秒）',
    'settings.serve.maxConcurrent': '最大并发请求',
    'settings.serve.sections.features': '功能开关',
    'settings.serve.featuresHint': '控制 serve 运行时暴露的模块和默认会话工具。',
    'settings.serve.sections.output': '输出与日志',
    'settings.serve.outputHint': '控制工具输出、系统提示处理和日志等级。',
    'settings.serve.toolMode': '工具输出模式',
    'settings.serve.toolDetail': '工具详情',
    'settings.serve.systemPromptMode': '系统提示处理',
    'settings.serve.logLevel': '日志等级',
    'settings.serve.sections.security': '安全',
    'settings.serve.securityHint': '认证、沙箱、CORS 和自动审批。',
    'settings.serve.auth': 'Bearer Token 认证',
    'settings.serve.sandbox': '沙箱',
    'settings.serve.sandboxLevel': '沙箱等级',
    'settings.serve.smartApprovals': '智能审批',
    'settings.serve.tokens': '认证 Token',
    'settings.serve.corsOrigins': 'CORS 来源',
    'settings.serve.sections.sessions': '会话池',
    'settings.serve.sessionsHint': '控制 API session 的空闲回收和容量。',
    'settings.serve.idleTimeout': '空闲超时（秒）',
    'settings.serve.maxSessions': '最大会话数',
    'settings.serve.sections.automation': '自动化与记忆',
    'settings.serve.automationHint': 'Cron 调度器和 memory.md 存储。',
    'settings.serve.cronInterval': 'Cron 间隔（秒）',
    'settings.serve.memoryPath': 'Memory 路径',
    'settings.serve.sections.agent': 'Agent 行为',
    'settings.serve.agentHint': '控制最大轮次和压力提示阈值。',
    'settings.serve.maxTurns': '最大轮次',
    'settings.serve.budgetThreshold': '预算压力阈值',
    'settings.serve.contextThreshold': '上下文压力阈值',
    'settings.serve.budgetPressure': '启用预算压力提示',
    'settings.serve.contextPressure': '启用上下文压力提示',
    'settings.serve.sections.channels': '消息通道',
    'settings.serve.channelsHint': '配置 WeChat / Feishu 通道基础参数。',
    'settings.serve.wechatCred': 'WeChat 凭据路径',
    'settings.serve.wechatWorkDir': 'WeChat 工作目录',
    'settings.serve.autoTyping': '自动输入提示',
    'settings.serve.feishuAppID': 'Feishu App ID',
    'settings.serve.feishuAppSecret': 'Feishu App Secret',
    'settings.serve.feishuWorkDir': 'Feishu 工作目录',
    'settings.serve.wechatUsers': 'WeChat 允许用户',
    'settings.serve.feishuUsers': 'Feishu 允许用户',
    'settings.serve.sections.hooks': 'Hooks',
    'settings.serve.hooksHint': '工具执行前后的外部脚本。',
    'settings.serve.preToolCall': 'Pre Tool Call',
    'settings.serve.postToolCall': 'Post Tool Call',
    'settings.serve.advancedJson': '高级 JSON',
    'settings.serve.advancedJsonHint': '保留未图形化字段；通常不需要直接编辑。',
    'settings.workdir.saved': '工作目录配置已保存。',
    'settings.workdir.title': '工作目录',
    'settings.workdir.mainHint': 'defaultWorkDir - 仅作为直接调用 OpenAI API 时的 fallback 目录',
    'settings.workdir.default': '默认工作目录（API fallback）',
    'settings.workdir.defaultHint': '当 /v1/chat/completions 没有 x_working_dir 且没有 session 时使用。Web UI 新会话仍由用户选择工作目录。',
    'settings.workdir.allowed': '可选择工作目录',
    'settings.workdir.allowedHint': 'allowedWorkDirs - Web UI 目录选择和 x_working_dir 的安全边界',
    'settings.workdir.restrict': '限制可选择目录',
    'settings.workdir.restrictHint': '开启后只能在下方目录及其子目录中选择；关闭时不限制目录覆盖。',
    'settings.workdir.noWhitelist': '未限制可选择目录。目录选择器会从默认工作目录打开，但可以继续浏览本机其他目录。',
    'settings.workdir.denyAll': '添加目录后才会启用限制。',
    'settings.workdir.arrayHint': '添加一个或多个根目录作为用户可选择的工作目录；不填写目录会保持未限制。',
    'chat.suggestion.projectSummary': '阅读当前项目并总结核心模块和调用链',
    'chat.suggestion.reviewChanges': '审查最近的代码改动，列出潜在回归风险',
    'chat.suggestion.addTests': '帮我为这个 Go 包补充关键单元测试',
    'chat.suggestion.fixTests': '定位测试失败原因并给出最小修复方案',
    'chat.suggestion.refactor': '重构这段代码，保持行为不变并降低复杂度',
    'chat.suggestion.configAudit': '检查配置文件和启动参数是否存在冲突',
    'chat.suggestion.readme': '为新增功能整理一份简洁的 README 说明',
    'chat.suggestion.multiAgent': '生成一个安全的多 Agent 任务拆解方案',
    'chat.error.modelNoImages': '当前模型不支持图片输入',
    'chat.error.needWorkDir': '请先选择本次会话的工作目录',
    'chat.error.unsupportedFileType': '不支持的文件类型：{name}',
    'chat.error.imageReadFailed': '读取图片失败：{name}',
    'chat.taskFailed': '任务失败',
    'chat.notice.stopped': '已停止请求。',
    'chat.welcome': '有什么我能帮你的吗？',
    'chat.you': '你',
    'chat.generating': '生成中',
    'chat.waitingModel': '正在等待模型响应...',
    'chat.plan': '任务计划',
    'chat.toolCall': '工具调用',
    'chat.toolEvents': '工具事件',
    'chat.sessionEvents': '会话事件',
    'chat.sessionEvents.idle': '空闲',
    'chat.sessionEvents.canceled': '已取消',
    'chat.sessionEvents.tokens': '{tokens} tokens',
    'chat.sessionEvents.cache': '缓存 {rate}',
    'chat.sessionEvents.capabilities': '能力 {count}',
    'chat.argsJson': '参数 JSON',
    'chat.loadingToolResult': '正在加载工具结果...',
    'chat.session': '会话',
    'chat.newSession': '新建会话',
    'chat.clearWorkDir': '清除',
    'chat.changeWorkDir': '更换目录',
    'chat.selectWorkDir': '选择工作目录',
    'chat.removeImage': '移除图片',
    'chat.apiDisabled': 'OpenAI API 已禁用',
    'chat.messagePlaceholder': '发消息...',
    'chat.uploadImage': '上传图片',
    'chat.selectModel': '选择模型',
    'chat.defaultModel': '默认模型',
    'chat.tools': '会话工具',
    'chat.toolToggle.webSearch': '为当前会话启用 webSearch',
    'chat.toolToggle.browser': '为当前会话启用 browser',
    'chat.toolToggle.a2aMaster': '为当前会话启用 a2aMaster',
    'chat.toolToggle.delegate': '为当前会话启用 delegate',
    'chat.toolToggle.multiAgent': '为当前会话启用 multi-agent',
    'chat.toolToggle.workflows': '为当前会话启用 workflow 工具',
    'chat.sending': '发送中',
    'chat.send': '发送',
    'chat.plan.done': '完成',
    'chat.plan.running': '进行中',
    'chat.plan.failed': '失败',
    'chat.plan.pending': '待处理',
    'chat.tool.result': '工具结果',
    'chat.tool.failed': '工具执行失败',
    'chat.tool.completed': '工具执行完成',
    'chat.tool.detailLoadFailed': '加载失败',
    'chat.tool.read.offset': '从第 {offset} 行',
    'chat.tool.read.limit': '最多 {limit} 行',
    'chat.tool.read.imageMode': '图片模式 {mode}',
    'chat.tool.read.maxLongEdge': '最长边 {value}px',
    'chat.tool.read.crop': '裁剪 {value}',
    'chat.tool.read.label': '读取文件',
    'chat.tool.read.missing': '(未指定文件)',
    'chat.tool.ls.label': '列出目录',
    'chat.tool.find.label': '查找文件',
    'chat.tool.find.missing': '(未指定 pattern)',
    'chat.tool.find.path': '目录 {path}',
    'chat.tool.find.maxDepth': '深度 {depth}',
    'chat.tool.find.maxResults': '最多 {count} 条',
    'chat.tool.find.pattern': '匹配模式',
    'chat.tool.find.searchPath': '搜索目录',
    'chat.tool.find.depth': '最大深度',
    'chat.tool.find.resultLimit': '结果上限',
    'chat.tool.grep.maxResults': '最多 {count} 条',
    'chat.tool.grep.label': '搜索文本',
    'chat.tool.grep.missing': '(未指定 pattern)',
    'chat.tool.bash.async': '后台运行',
    'chat.tool.bash.noTimeout': '无工具超时',
    'chat.tool.bash.timeout': '超时 {seconds}s',
    'chat.tool.bash.label': '执行命令',
    'chat.tool.bash.missing': '(未指定命令)',
    'chat.tool.edit.label': '编辑文件',
    'chat.tool.edit.missing': '(未指定文件)',
    'chat.tool.edit.oneEdit': '1 处替换',
    'chat.tool.edit.manyEdits': '{count} 处替换',
    'chat.tool.edit.editNumber': '替换 #{number}',
    'chat.tool.edit.lineChange': '{old} 行 -> {next} 行',
    'chat.tool.edit.oldText': '原文本',
    'chat.tool.edit.newText': '新文本',
    'chat.tool.edit.empty': '(空)',
    'chat.tool.write.label': '写入文件',
    'chat.tool.write.missing': '(未指定文件)',
    'chat.tool.write.lines': '{count} 行',
    'chat.tool.write.chars': '{count} 字符',
    'chat.tool.write.summary': '{lines} 行 / {chars} 字符',
    'chat.tool.write.preview': '写入预览',
    'chat.tool.write.content': '内容',
    'chat.tool.browser.label': '浏览器',
    'chat.tool.browser.missing': '(未指定目标)',
    'chat.tool.browser.action': '动作',
    'chat.tool.browser.url': 'URL',
    'chat.tool.browser.selectorLabel': '选择器',
    'chat.tool.browser.selector': '选择器 {selector}',
    'chat.tool.browser.output': '输出 {path}',
    'chat.tool.browser.fullPage': '整页截图',
    'chat.tool.browser.interactive': '交互快照',
    'chat.tool.browser.viewport': '视口 {width}x{height}',
    'chat.tool.browser.value': '值',
    'chat.tool.browser.expression': '表达式',
    'chat.tool.skillRef.label': '加载 Skill 引用',
    'chat.tool.skillRef.missing': '(未指定引用)',
    'chat.tool.skillRef.skill': 'Skill {skill}',
    'chat.tool.skillRef.ref': '引用 {ref}',
    'chat.tool.skillRef.skillLabel': 'Skill',
    'chat.tool.skillRef.refLabel': '引用',
    'chat.tool.workflowLint.label': '校验 Workflow',
    'chat.tool.workflowLint.missing': '(未提供 source)',
    'chat.tool.workflowLint.lines': '{count} 行',
    'chat.tool.workflowLint.chars': '{count} 字符',
    'chat.tool.workflowLint.source': 'Workflow 源码',
    'chat.tool.workflowLint.valid': '校验通过',
    'chat.tool.workflowLint.invalid': '校验失败',
    'chat.tool.workflowLint.tasks': '任务',
    'chat.tool.workflowLint.results': '结果引用',
    'chat.tool.subagent.delegate': '委派 SubAgent',
    'chat.tool.subagent.spawn': '启动 SubAgent',
    'chat.tool.subagent.status': '检查 SubAgent',
    'chat.tool.subagent.destroy': '销毁 SubAgent',
    'chat.tool.subagent.send': '发送给 SubAgent',
    'chat.tool.subagent.taskMissing': '(未指定任务)',
    'chat.tool.subagent.handleMissing': '(未指定 handle)',
    'chat.tool.subagent.mode': '模式 {mode}',
    'chat.tool.subagent.workDir': '目录 {path}',
    'chat.tool.subagent.tools': '工具 {tools}',
    'chat.tool.subagent.maxIterations': '最多 {count} 轮',
    'chat.tool.subagent.task': '任务',
    'chat.tool.subagent.handle': 'Handle',
    'chat.tool.subagent.message': '消息',
    'chat.tool.subagent.statusLabel': '状态',
    'chat.tool.subagent.duration': '耗时',
    'chat.tool.subagent.toolCalls': '工具调用',
    'chat.subagents.title': 'SubAgents',
    'chat.subagents.subtitle': '{count} 个子 agent',
    'chat.subagents.running': '{count}/{total} 运行中',
    'chat.subagents.failed': '{count}/{total} 失败',
    'chat.subagents.done': '{count}/{total} 完成',
    'chat.subagents.destroyed': '已销毁',
    'chat.subagents.open': '查看历史',
    'chat.subagents.history': 'SubAgent 历史',
    'chat.subagents.loading': '正在加载 SubAgent 历史...',
    'chat.subagents.empty': '暂无可展示的 SubAgent 历史'
  },
  en: {
    'app.name': 'MothX',
    'app.local': 'Local runtime',
    'app.unknownPage': 'Unknown page',
    'common.add': 'Add',
    'common.clear': 'Clear',
    'common.close': 'Close',
    'common.completed': 'Completed',
    'common.connected': 'Connected',
    'common.count': '{count}',
    'common.create': 'Create',
    'common.delete': 'Delete',
    'common.disabled': 'Off',
    'common.disabledState': 'Disabled',
    'common.disconnected': 'Disconnected',
    'common.enable': 'Enable',
    'common.disable': 'Disable',
    'common.enabled': 'On',
    'common.failed': 'Failed',
    'common.first': 'First',
    'common.idle': 'Idle',
    'common.items': '{count} items',
    'common.last': 'Last',
    'common.loading': 'Loading...',
    'common.next': 'Next {time}',
    'common.nextPage': 'Next',
    'common.no': 'No',
    'common.open': 'Open',
    'common.pending': 'Pending',
    'common.previous': 'Prev',
    'common.refresh': 'Refresh',
    'common.remove': 'Remove',
    'common.running': 'Running',
    'common.save': 'Save',
    'common.stop': 'Stop',
    'common.times': '{count} runs',
    'common.uninitialized': 'Uninitialized',
    'common.yes': 'Yes',
    'nav.newChat': 'New Chat',
    'nav.sessions': 'Sessions',
    'nav.skills': 'Skills',
    'nav.stats': 'Stats',
    'nav.cron': 'Cron',
    'nav.channels': 'Channels',
    'nav.logs': 'Logs',
    'nav.settings': 'Settings',
    'sidebar.search': 'Search sessions...',
    'sidebar.history': 'Sessions',
    'sidebar.all': 'All',
    'sidebar.defaultSession': 'Default session',
    'sidebar.noHistory': 'No history',
    'sidebar.noMatches': 'No matching sessions',
    'sidebar.stats': 'Stats',
    'sidebar.stats.requests': 'Requests',
    'sidebar.stats.tokens': 'Tokens',
    'sidebar.stats.input': 'Input',
    'sidebar.stats.output': 'Output',
    'channels.title': 'Message Channels',
    'channels.name': 'Name',
    'channels.enabled': 'Enabled',
    'channels.status': 'Status',
    'channels.empty': 'No channels',
    'settings.channels.saved': 'Channel config saved.',
    'settings.channels.configure': 'Configure',
    'settings.channels.websocketHint': 'Local WebSocket channel. Enabling mounts /ws immediately.',
    'settings.channels.websocketToggle': 'Enable WebSocket channel',
    'settings.channels.websocketEnabled': 'WebSocket channel enabled.',
    'settings.channels.websocketDisabled': 'WebSocket channel disabled.',
    'settings.channels.feishuHint': 'Feishu long connection requires App ID and App Secret.',
    'settings.channels.feishuConfig': 'Configure Feishu',
    'settings.channels.feishuConfigHint': 'Saved to serve.json and synced to the running process immediately.',
    'settings.channels.feishuKeyRequired': 'App ID and App Secret are required to enable Feishu.',
    'settings.channels.feishuSaved': 'Feishu config saved.',
    'settings.channels.wechatHint': 'WeChat requires QR login. The channel is enabled after confirmation.',
    'settings.channels.wechatSaved': 'WeChat config saved.',
    'settings.channels.wechatDisabled': 'WeChat channel disabled.',
    'settings.channels.wechatEnabled': 'WeChat login confirmed; channel enabled.',
    'settings.channels.wechatScanEnable': 'Scan to Enable',
    'settings.channels.wechatRelogin': 'Scan Again',
    'settings.channels.wechatLogin': 'WeChat QR Login',
    'settings.channels.wechatLoginHint': 'Open the QR code in a new tab, then scan with WeChat and confirm on your phone.',
    'settings.channels.wechatOpenQrHint': 'The QR code is ready. Open it in a new tab from the button below.',
    'settings.channels.wechatNoQr': 'QR code has not been generated.',
    'settings.channels.refreshQr': 'Refresh QR',
    'settings.channels.openQrTab': 'Open QR in New Tab',
    'settings.channels.popupBlocked': 'The browser blocked the new tab. Use "Open QR in New Tab".',
    'settings.channels.wechatState.idle': 'Not logged in',
    'settings.channels.wechatState.starting': 'Generating QR',
    'settings.channels.wechatState.pending': 'Waiting for scan',
    'settings.channels.wechatState.scanned': 'Scanned, waiting for confirmation',
    'settings.channels.wechatState.confirmed': 'Logged in',
    'settings.channels.wechatState.expired': 'QR expired',
    'settings.channels.wechatState.error': 'Login failed',
    'settings.channels.wechatState.cancelled': 'Cancelled',
    'logs.filter': 'Filter log content',
    'logs.connect': 'Connect',
    'logs.disconnect': 'Disconnect',
    'logs.empty': 'No logs',
    'sessions.deleted': 'Session {id} deleted',
    'sessions.filter': 'Filter sessions (ID / workdir / title)',
    'sessions.session': 'Session',
    'sessions.workDir': 'WorkDir',
    'sessions.status': 'Status',
    'sessions.messageCount': 'Messages',
    'sessions.active': 'Running',
    'sessions.history': 'History',
    'sessions.empty': 'No sessions to show',
    'sessions.pageRange': '{start}-{end} / {total}',
    'stats.range': 'Stats range',
    'stats.range.today': 'Today',
    'stats.range.week': 'Last 7 days',
    'stats.range.month': 'Last 30 days',
    'stats.range.all': 'All time',
    'stats.loadFailed': 'Failed to load stats',
    'stats.requests': 'Requests',
    'stats.totalTokens': 'Total Tokens',
    'stats.inputTokens': 'Input Tokens',
    'stats.outputTokens': 'Output Tokens',
    'stats.trend': 'Usage Trend',
    'stats.providers': 'Providers',
    'stats.models': 'Models',
    'stats.recent': 'Recent Requests',
    'stats.empty': 'No stats yet',
    'stats.time': 'Time',
    'stats.model': 'Model',
    'stats.provider': 'Provider',
    'stats.input': 'Input',
    'stats.output': 'Output',
    'stats.duration': 'Duration',
    'stats.pageInfo': '{page} / {total}',
    'cron.created': 'Cron task created',
    'cron.deleted': 'Task {id} deleted',
    'cron.newTask': 'New Task',
    'cron.name': 'Name',
    'cron.namePlaceholder': 'Daily summary',
    'cron.schedule': 'Schedule',
    'cron.schedulePlaceholder': '@daily or 0 9 * * *',
    'cron.mode': 'Mode',
    'cron.oneshot': 'One-shot',
    'cron.promptPlaceholder': 'Instruction to run...',
    'cron.list': 'Task List',
    'cron.empty': 'No tasks',
    'dirBrowser.title': 'Select WorkDir',
    'dirBrowser.up': 'Up',
    'dirBrowser.loading': 'Loading...',
    'dirBrowser.empty': 'No subdirectories',
    'dirBrowser.cancel': 'Cancel',
    'dirBrowser.select': 'Select This Directory',
    'prefs.language': 'Language',
    'prefs.theme': 'Theme',
    'prefs.zh': '中',
    'prefs.en': 'EN',
    'prefs.light': 'Light',
    'prefs.dark': 'Dark',
    'prefs.auto': 'Auto',
    'prefs.preferences': 'Preferences',
    'topbar.chat.subtitle': 'AI output may be wrong; verify important details',
    'topbar.sessions.subtitle': 'Manage all session history',
    'topbar.skills.subtitle': 'Browse, install, and activate SkillHub / ClawHub skills',
    'topbar.stats.subtitle': 'Review requests, tokens, models, and provider usage',
    'topbar.cron.subtitle': 'Schedule automated tasks',
    'topbar.channels.subtitle': 'External messaging channel status',
    'topbar.logs.subtitle': 'Live log stream',
    'topbar.settings.subtitle': 'Serve / Providers / App / Memory configuration',
    'topbar.openLogs': 'Open Logs',
    'topbar.closeLogs': 'Close Logs',
    'topbar.refresh': 'Refresh',
    'skills.market': 'Marketplace',
    'skills.view': 'View',
    'skills.browse': 'Browse',
    'skills.search': 'Search',
    'skills.official': 'Official',
    'skills.searchPlaceholder': 'Search skills by name or purpose...',
    'skills.scope': 'Install scope',
    'skills.scope.project': 'Current project',
    'skills.scope.global': 'Global',
    'skills.category': 'Category',
    'skills.allCategories': 'All categories',
    'skills.sort': 'Sort',
    'skills.downloads': 'Downloads',
    'skills.installs': 'Installs',
    'skills.updatedAt': 'Updated',
    'skills.results': 'Skills',
    'skills.empty': 'No matching skills',
    'skills.page': 'Page {page}',
    'skills.detail': 'Skill detail',
    'skills.notAvailable': 'Not available',
    'skills.noDescription': 'No description',
    'skills.install': 'Install',
    'skills.installActivate': 'Install & Activate',
    'skills.update': 'Update',
    'skills.activate': 'Activate',
    'skills.active': 'Active in this session',
    'skills.source': 'Source',
    'skills.downloadSources': 'Download sources',
    'skills.fallback': 'fallback',
    'skills.files': 'Files',
    'skills.security': 'Security report',
    'skills.evaluation': 'Evaluation',
    'skills.select': 'Select a skill from the list to inspect it',
    'skills.installed': 'Installed {name}',
    'skills.updated': 'Updated {name}',
    'skills.activated': 'Activated {name} in the current session',
    'settings.tabs.overview': 'Overview',
    'settings.tabs.serve': 'Serve Config',
    'settings.tabs.workdir': 'WorkDirs',
    'settings.tabs.providers': 'Providers',
    'settings.tabs.app': 'App Settings',
    'settings.tabs.memory': 'Memory',
    'settings.tabs.features': 'Features',
    'settings.tabs.channels': 'Channels',
    'settings.tabs.logs': 'Logs',
    'settings.unknown': 'Unknown settings group',
    'settings.overview.serve.desc': 'Runtime configuration for HTTP listening, channels, and the WebUI static directory.',
    'settings.overview.providers.desc': 'Default provider, default model, model parameters, and all provider/model configuration.',
    'settings.overview.app.desc': 'Application settings for mode, approval policy, tools, and context compaction.',
    'settings.overview.memory.desc': 'Enable and edit long-term memory in memory.md.',
    'settings.overview.channels.desc': 'Configure WebSocket, Feishu, and WeChat QR channels.',
    'settings.overview.features.desc': 'Toggle API, WebSocket, Cron, Memory, and related modules.',
    'settings.runtime.title': 'Runtime Info',
    'settings.runtime.version': 'Version',
    'settings.runtime.listen': 'Listen',
    'settings.runtime.sessions': 'Sessions',
    'settings.runtime.api': 'OpenAI API',
    'settings.features.hint': 'Read-only view. Change these in Serve Config or App Settings.',
    'settings.features.feature': 'Feature',
    'settings.features.status': 'Status',
    'settings.features.description': 'Description',
    'settings.features.api.label': 'OpenAI-compatible API',
    'settings.features.api.desc': 'Allows calls through /v1/chat/completions.',
    'settings.features.webUI.label': 'Web UI',
    'settings.features.webUI.desc': 'This interface, served from the Serve static asset directory.',
    'settings.features.websocket.label': 'WebSocket Logs',
    'settings.features.websocket.desc': 'Live log streaming through /ws/logs.',
    'settings.features.cron.label': 'Cron Tasks',
    'settings.features.cron.desc': 'Scheduler backed by the local task list.',
    'settings.features.memory.label': 'Memory',
    'settings.features.memory.desc': 'Long-term memory in memory.md.',
    'settings.features.multiAgent.label': 'Multi Agent',
    'settings.features.multiAgent.desc': 'Enables spawn / send / destroy sub-agent tools.',
    'settings.memory.saved': 'Memory saved.',
    'settings.memory.notInitialized': 'Not initialized',
    'settings.providers.saved': 'Provider settings saved.',
    'settings.providers.hint': 'Default provider/model, global model parameters, and all Provider/Model configuration.',
    'settings.providers.sections.defaults': 'Default Model',
    'settings.providers.defaultsHint': 'Controls the default provider, default model, default thinking level, and global token limits.',
    'settings.app.saved': 'App settings saved.',
    'settings.app.hint': '/api/settings - Approval / Context / Tools, etc.',
    'settings.app.parseError': 'Current settings JSON cannot be parsed: {error}',
    'settings.app.sections.defaults': 'Defaults',
    'settings.app.defaultsHint': 'Runtime mode, directories, and startup defaults.',
    'settings.app.defaultProvider': 'Default Provider',
    'settings.app.defaultModel': 'Default Model',
    'settings.app.defaultMode': 'Default Mode',
    'settings.app.thinking': 'Default Thinking',
    'settings.app.maxContextTokens': 'Max Context Tokens',
    'settings.app.maxOutputTokens': 'Max Output Tokens',
    'settings.app.skillsDir': 'Skills Dir',
    'settings.app.sessionDir': 'Session Dir',
    'settings.app.shellPath': 'Shell Path',
    'settings.app.shellPrefix': 'Shell Prefix',
    'settings.app.enablePlanTool': 'Plan Tool',
    'settings.app.updateCheck': 'Update Check',
    'settings.app.sections.context': 'Context & Compaction',
    'settings.app.contextHint': 'Context files, compaction windows, and idle compression.',
    'settings.app.contextFiles': 'Enable Context Files',
    'settings.app.compaction': 'Enable Compaction',
    'settings.app.reserveTokens': 'Reserve Tokens',
    'settings.app.keepRecentTokens': 'Keep Recent Tokens',
    'settings.app.tokenizer': 'Tokenizer',
    'settings.app.tokenizerModel': 'Tokenizer Model',
    'settings.app.idleCompression': 'Idle Compression',
    'settings.app.idleTimeout': 'Idle Timeout (s)',
    'settings.app.idleMinTokens': 'Idle Min Tokens',
    'settings.app.compactionTemplate': 'Compaction Template',
    'settings.app.extraFiles': 'Extra Context Files',
    'settings.app.sections.tools': 'Tools & Status',
    'settings.app.toolsHint': 'Web Search, retry, and status line behavior.',
    'settings.app.webSearch': 'Web Search',
    'settings.app.webSearchProvider': 'Search Provider',
    'settings.app.webSearchType': 'Provider Type',
    'settings.app.webSearchModel': 'Search Model',
    'settings.app.retry': 'Enable Retry',
    'settings.app.maxRetries': 'Max Retries',
    'settings.app.baseDelay': 'Base Delay (ms)',
    'settings.app.statusLine': 'Enable Status Line',
    'settings.app.statusLineType': 'Status Line Type',
    'settings.app.statusLineCommand': 'Status Line Command',
    'settings.app.statusLineTimeout': 'Status Line Timeout (ms)',
    'settings.app.statusLineFallback': 'Status Line Fallback',
    'settings.app.sections.safety': 'Safety & Approval',
    'settings.app.safetyHint': 'Sandbox path boundaries, network access, and approval rules.',
    'settings.app.sandbox': 'Enable Sandbox',
    'settings.app.allowNetwork': 'Allow Network',
    'settings.app.sandboxLevel': 'Sandbox Level',
    'settings.app.bwrapPath': 'bwrap Path',
    'settings.app.tmpSize': 'Tmp Size',
    'settings.app.confirmBeforeWrite': 'Confirm Before Write',
    'settings.app.allowedRead': 'Allowed Read Paths',
    'settings.app.allowedWrite': 'Allowed Write Paths',
    'settings.app.deniedPaths': 'Denied Paths',
    'settings.app.passEnv': 'Pass Env',
    'settings.app.bashWhitelist': 'Bash Auto-approve Prefixes',
    'settings.app.bashBlacklist': 'Bash Force-approval Prefixes',
    'settings.app.sections.providers': 'Providers',
    'settings.app.providersHint': '{count} providers. Advanced fields are preserved in JSON.',
    'settings.app.noProviders': 'No providers configured',
    'settings.app.unnamedProvider': 'Unnamed Provider',
    'settings.app.providerID': 'Provider ID',
    'settings.app.providerVendor': 'Vendor',
    'settings.app.providerAPI': 'API Type',
    'settings.app.providerThinkingFormat': 'Thinking Format',
    'settings.app.providerBaseURL': 'Base URL',
    'settings.app.providerAPIKey': 'API Key',
    'settings.app.httpProxy': 'HTTP Proxy',
    'settings.app.forceHTTP11': 'Force HTTP/1.1',
    'settings.app.cacheControl': 'Cache Control',
    'settings.app.reasoningSummary': 'Reasoning Summary',
    'settings.app.promptCacheKey': 'Prompt Cache Key',
    'settings.app.promptCacheRetention': 'Prompt Cache Retention',
    'settings.app.addHeader': 'Add Header',
    'settings.app.addModel': 'Add Model',
    'settings.app.headers': 'Headers',
    'settings.app.models': 'Models',
    'settings.app.modelID': 'Model ID',
    'settings.app.modelName': 'Display',
    'settings.app.modelContext': 'Context',
    'settings.app.modelMaxTokens': 'Max Output',
    'settings.app.modelTemperature': 'Temp',
    'settings.app.modelTopP': 'Top P',
    'settings.app.modelInput': 'Input',
    'settings.app.modelReasoning': 'Reasoning',
    'settings.app.modelActions': 'Actions',
    'settings.app.advancedJson': 'Advanced JSON',
    'settings.app.advancedJsonHint': 'Preserves fields not covered by the form. Usually no direct editing is needed.',
    'settings.serve.saved': 'Serve config saved. Listen or channel changes require restart.',
    'settings.serve.sections.runtime': 'Runtime',
    'settings.serve.runtimeHint': 'Listen address, default model, and request limits. Listen changes usually require restart.',
    'settings.serve.listen': 'Listen Address',
    'settings.serve.webuiDir': 'Web UI Dir',
    'settings.serve.provider': 'Default Provider',
    'settings.serve.model': 'Default Model',
    'settings.serve.defaultMode': 'Default Mode',
    'settings.serve.thinking': 'Default Thinking',
    'settings.serve.timeout': 'Request Timeout (s)',
    'settings.serve.maxConcurrent': 'Max Concurrent Requests',
    'settings.serve.sections.features': 'Features',
    'settings.serve.featuresHint': 'Controls serve modules and default session tools.',
    'settings.serve.sections.output': 'Output & Logs',
    'settings.serve.outputHint': 'Controls tool output, system prompt handling, and log level.',
    'settings.serve.toolMode': 'Tool Output Mode',
    'settings.serve.toolDetail': 'Tool Detail',
    'settings.serve.systemPromptMode': 'System Prompt Mode',
    'settings.serve.logLevel': 'Log Level',
    'settings.serve.sections.security': 'Security',
    'settings.serve.securityHint': 'Authentication, sandboxing, CORS, and smart approvals.',
    'settings.serve.auth': 'Bearer Token Auth',
    'settings.serve.sandbox': 'Sandbox',
    'settings.serve.sandboxLevel': 'Sandbox Level',
    'settings.serve.smartApprovals': 'Smart Approvals',
    'settings.serve.tokens': 'Auth Tokens',
    'settings.serve.corsOrigins': 'CORS Origins',
    'settings.serve.sections.sessions': 'Session Pool',
    'settings.serve.sessionsHint': 'Controls API session idle cleanup and capacity.',
    'settings.serve.idleTimeout': 'Idle Timeout (s)',
    'settings.serve.maxSessions': 'Max Sessions',
    'settings.serve.sections.automation': 'Automation & Memory',
    'settings.serve.automationHint': 'Cron scheduler and memory.md storage.',
    'settings.serve.cronInterval': 'Cron Interval (s)',
    'settings.serve.memoryPath': 'Memory Path',
    'settings.serve.sections.agent': 'Agent Behavior',
    'settings.serve.agentHint': 'Controls maximum turns and pressure thresholds.',
    'settings.serve.maxTurns': 'Max Turns',
    'settings.serve.budgetThreshold': 'Budget Pressure Threshold',
    'settings.serve.contextThreshold': 'Context Pressure Threshold',
    'settings.serve.budgetPressure': 'Enable Budget Pressure',
    'settings.serve.contextPressure': 'Enable Context Pressure',
    'settings.serve.sections.channels': 'Channels',
    'settings.serve.channelsHint': 'Base settings for WeChat / Feishu channels.',
    'settings.serve.wechatCred': 'WeChat Credential Path',
    'settings.serve.wechatWorkDir': 'WeChat WorkDir',
    'settings.serve.autoTyping': 'Auto Typing',
    'settings.serve.feishuAppID': 'Feishu App ID',
    'settings.serve.feishuAppSecret': 'Feishu App Secret',
    'settings.serve.feishuWorkDir': 'Feishu WorkDir',
    'settings.serve.wechatUsers': 'WeChat Allowed Users',
    'settings.serve.feishuUsers': 'Feishu Allowed Users',
    'settings.serve.sections.hooks': 'Hooks',
    'settings.serve.hooksHint': 'External scripts before and after tool execution.',
    'settings.serve.preToolCall': 'Pre Tool Call',
    'settings.serve.postToolCall': 'Post Tool Call',
    'settings.serve.advancedJson': 'Advanced JSON',
    'settings.serve.advancedJsonHint': 'Preserves fields not covered by the form. Usually no direct editing is needed.',
    'settings.workdir.saved': 'WorkDir config saved.',
    'settings.workdir.title': 'WorkDir',
    'settings.workdir.mainHint': 'defaultWorkDir - fallback directory only for direct OpenAI API calls',
    'settings.workdir.default': 'Default WorkDir (API fallback)',
    'settings.workdir.defaultHint': 'Used when /v1/chat/completions has no x_working_dir and no session. New Web UI sessions still choose their own workdir.',
    'settings.workdir.allowed': 'Selectable WorkDirs',
    'settings.workdir.allowedHint': 'allowedWorkDirs - Security boundary for Web UI directory selection and x_working_dir',
    'settings.workdir.restrict': 'Restrict selectable directories',
    'settings.workdir.restrictHint': 'When enabled, selection is limited to the directories below and their children. When disabled, workdir overrides are unrestricted.',
    'settings.workdir.noWhitelist': 'Selectable directories are unrestricted. The picker opens at the default workdir, but can browse other local directories.',
    'settings.workdir.denyAll': 'Add a directory to enable the restriction.',
    'settings.workdir.arrayHint': 'Add one or more root directories users can choose from. Leaving the list empty keeps selection unrestricted.',
    'chat.suggestion.projectSummary': 'Read the current project and summarize core modules and call chains',
    'chat.suggestion.reviewChanges': 'Review recent code changes and list regression risks',
    'chat.suggestion.addTests': 'Add key unit tests for this Go package',
    'chat.suggestion.fixTests': 'Find why tests fail and propose the smallest fix',
    'chat.suggestion.refactor': 'Refactor this code while preserving behavior and reducing complexity',
    'chat.suggestion.configAudit': 'Check config files and launch args for conflicts',
    'chat.suggestion.readme': 'Write a concise README note for the new feature',
    'chat.suggestion.multiAgent': 'Create a safe multi-agent task breakdown',
    'chat.error.modelNoImages': 'The current model does not support image input',
    'chat.error.needWorkDir': 'Choose a workdir for this session first',
    'chat.error.unsupportedFileType': 'Unsupported file type: {name}',
    'chat.error.imageReadFailed': 'Failed to read image: {name}',
    'chat.taskFailed': 'Task failed',
    'chat.notice.stopped': 'Request stopped.',
    'chat.welcome': 'What can I help with?',
    'chat.you': 'You',
    'chat.generating': 'Generating',
    'chat.waitingModel': 'Waiting for model response...',
    'chat.plan': 'Plan',
    'chat.toolCall': 'Tool Call',
    'chat.toolEvents': 'Tool Events',
    'chat.sessionEvents': 'Session Events',
    'chat.sessionEvents.idle': 'Idle',
    'chat.sessionEvents.canceled': 'Canceled',
    'chat.sessionEvents.tokens': '{tokens} tokens',
    'chat.sessionEvents.cache': 'Cache {rate}',
    'chat.sessionEvents.capabilities': 'Caps {count}',
    'chat.argsJson': 'Args JSON',
    'chat.loadingToolResult': 'Loading tool result...',
    'chat.session': 'Session',
    'chat.newSession': 'New Session',
    'chat.clearWorkDir': 'Clear',
    'chat.changeWorkDir': 'Change WorkDir',
    'chat.selectWorkDir': 'Select WorkDir',
    'chat.removeImage': 'Remove image',
    'chat.apiDisabled': 'OpenAI API is disabled',
    'chat.messagePlaceholder': 'Send a message...',
    'chat.uploadImage': 'Upload image',
    'chat.selectModel': 'Select model',
    'chat.defaultModel': 'Default model',
    'chat.tools': 'Session tools',
    'chat.toolToggle.webSearch': 'Enable webSearch for this session',
    'chat.toolToggle.browser': 'Enable browser for this session',
    'chat.toolToggle.a2aMaster': 'Enable a2aMaster for this session',
    'chat.toolToggle.delegate': 'Enable delegate for this session',
    'chat.toolToggle.multiAgent': 'Enable multi-agent for this session',
    'chat.toolToggle.workflows': 'Enable workflow tools for this session',
    'chat.sending': 'Sending',
    'chat.send': 'Send',
    'chat.plan.done': 'Done',
    'chat.plan.running': 'Running',
    'chat.plan.failed': 'Failed',
    'chat.plan.pending': 'Pending',
    'chat.tool.result': 'Tool result',
    'chat.tool.failed': 'Tool execution failed',
    'chat.tool.completed': 'Tool execution completed',
    'chat.tool.detailLoadFailed': 'Load failed',
    'chat.tool.read.offset': 'From line {offset}',
    'chat.tool.read.limit': 'Up to {limit} lines',
    'chat.tool.read.imageMode': 'Image mode {mode}',
    'chat.tool.read.maxLongEdge': 'Max long edge {value}px',
    'chat.tool.read.crop': 'Crop {value}',
    'chat.tool.read.label': 'Read File',
    'chat.tool.read.missing': '(file not specified)',
    'chat.tool.ls.label': 'List Directory',
    'chat.tool.find.label': 'Find Files',
    'chat.tool.find.missing': '(pattern not specified)',
    'chat.tool.find.path': 'Path {path}',
    'chat.tool.find.maxDepth': 'Depth {depth}',
    'chat.tool.find.maxResults': 'Up to {count} results',
    'chat.tool.find.pattern': 'Pattern',
    'chat.tool.find.searchPath': 'Search Path',
    'chat.tool.find.depth': 'Max Depth',
    'chat.tool.find.resultLimit': 'Result Limit',
    'chat.tool.grep.maxResults': 'Up to {count} results',
    'chat.tool.grep.label': 'Search Text',
    'chat.tool.grep.missing': '(pattern not specified)',
    'chat.tool.bash.async': 'Run in background',
    'chat.tool.bash.noTimeout': 'No tool timeout',
    'chat.tool.bash.timeout': 'Timeout {seconds}s',
    'chat.tool.bash.label': 'Run Command',
    'chat.tool.bash.missing': '(command not specified)',
    'chat.tool.edit.label': 'Edit File',
    'chat.tool.edit.missing': '(file not specified)',
    'chat.tool.edit.oneEdit': '1 replacement',
    'chat.tool.edit.manyEdits': '{count} replacements',
    'chat.tool.edit.editNumber': 'Replacement #{number}',
    'chat.tool.edit.lineChange': '{old} lines -> {next} lines',
    'chat.tool.edit.oldText': 'Old Text',
    'chat.tool.edit.newText': 'New Text',
    'chat.tool.edit.empty': '(empty)',
    'chat.tool.write.label': 'Write File',
    'chat.tool.write.missing': '(file not specified)',
    'chat.tool.write.lines': '{count} lines',
    'chat.tool.write.chars': '{count} chars',
    'chat.tool.write.summary': '{lines} lines / {chars} chars',
    'chat.tool.write.preview': 'Write Preview',
    'chat.tool.write.content': 'Content',
    'chat.tool.browser.label': 'Browser',
    'chat.tool.browser.missing': '(target not specified)',
    'chat.tool.browser.action': 'Action',
    'chat.tool.browser.url': 'URL',
    'chat.tool.browser.selectorLabel': 'Selector',
    'chat.tool.browser.selector': 'Selector {selector}',
    'chat.tool.browser.output': 'Output {path}',
    'chat.tool.browser.fullPage': 'Full page',
    'chat.tool.browser.interactive': 'Interactive snapshot',
    'chat.tool.browser.viewport': 'Viewport {width}x{height}',
    'chat.tool.browser.value': 'Value',
    'chat.tool.browser.expression': 'Expression',
    'chat.tool.skillRef.label': 'Load Skill Ref',
    'chat.tool.skillRef.missing': '(reference not specified)',
    'chat.tool.skillRef.skill': 'Skill {skill}',
    'chat.tool.skillRef.ref': 'Ref {ref}',
    'chat.tool.skillRef.skillLabel': 'Skill',
    'chat.tool.skillRef.refLabel': 'Ref',
    'chat.tool.workflowLint.label': 'Lint Workflow',
    'chat.tool.workflowLint.missing': '(source not provided)',
    'chat.tool.workflowLint.lines': '{count} lines',
    'chat.tool.workflowLint.chars': '{count} chars',
    'chat.tool.workflowLint.source': 'Workflow Source',
    'chat.tool.workflowLint.valid': 'Valid',
    'chat.tool.workflowLint.invalid': 'Invalid',
    'chat.tool.workflowLint.tasks': 'Tasks',
    'chat.tool.workflowLint.results': 'Result refs',
    'chat.tool.subagent.delegate': 'Delegate SubAgent',
    'chat.tool.subagent.spawn': 'Spawn SubAgent',
    'chat.tool.subagent.status': 'Check SubAgent',
    'chat.tool.subagent.destroy': 'Destroy SubAgent',
    'chat.tool.subagent.send': 'Send to SubAgent',
    'chat.tool.subagent.taskMissing': '(task not specified)',
    'chat.tool.subagent.handleMissing': '(handle not specified)',
    'chat.tool.subagent.mode': 'Mode {mode}',
    'chat.tool.subagent.workDir': 'WorkDir {path}',
    'chat.tool.subagent.tools': 'Tools {tools}',
    'chat.tool.subagent.maxIterations': 'Up to {count} turns',
    'chat.tool.subagent.task': 'Task',
    'chat.tool.subagent.handle': 'Handle',
    'chat.tool.subagent.message': 'Message',
    'chat.tool.subagent.statusLabel': 'Status',
    'chat.tool.subagent.duration': 'Duration',
    'chat.tool.subagent.toolCalls': 'Tool calls',
    'chat.subagents.title': 'SubAgents',
    'chat.subagents.subtitle': '{count} sub-agents',
    'chat.subagents.running': '{count}/{total} running',
    'chat.subagents.failed': '{count}/{total} failed',
    'chat.subagents.done': '{count}/{total} done',
    'chat.subagents.destroyed': 'Destroyed',
    'chat.subagents.open': 'View history',
    'chat.subagents.history': 'SubAgent History',
    'chat.subagents.loading': 'Loading SubAgent history...',
    'chat.subagents.empty': 'No SubAgent history to show'
  }
};

const isBrowser = typeof window !== 'undefined';
const mediaQuery = isBrowser && typeof window.matchMedia === 'function'
  ? window.matchMedia('(prefers-color-scheme: dark)')
  : null;

function loadPreference(key, fallback, allowed) {
  if (!isBrowser) return fallback;
  const value = window.localStorage.getItem(key);
  return allowed.includes(value) ? value : fallback;
}

export const language = writable(loadPreference(storageKeys.language, 'zh', ['zh', 'en']));
export const themeMode = writable(loadPreference(storageKeys.themeMode, 'auto', ['light', 'dark', 'auto']));
export const effectiveTheme = writable(resolveEffectiveTheme(loadPreference(storageKeys.themeMode, 'auto', ['light', 'dark', 'auto'])));

export const t = derived(language, ($language) => {
  const dict = dictionaries[$language] || dictionaries.zh;
  return (key, params) => formatTemplate(dict[key] || dictionaries.zh[key] || key, params);
});

function formatTemplate(template, params) {
  if (!params || typeof params !== 'object') return template;
  return template.replace(/\{([a-zA-Z0-9_]+)\}/g, (match, key) => {
    const value = params[key];
    return value === undefined || value === null ? match : String(value);
  });
}

export function setLanguage(value) {
  if (!['zh', 'en'].includes(value)) return;
  language.set(value);
  if (isBrowser) window.localStorage.setItem(storageKeys.language, value);
}

export function setThemeMode(value) {
  if (!['light', 'dark', 'auto'].includes(value)) return;
  themeMode.set(value);
  if (isBrowser) window.localStorage.setItem(storageKeys.themeMode, value);
  applyTheme(value);
}

function resolveEffectiveTheme(mode) {
  if (mode === 'dark' || mode === 'light') return mode;
  return mediaQuery?.matches ? 'dark' : 'light';
}

function applyTheme(mode) {
  const theme = resolveEffectiveTheme(mode);
  effectiveTheme.set(theme);
  if (!isBrowser) return;
  document.documentElement.dataset.theme = theme;
  document.documentElement.dataset.themeMode = mode;
}

if (isBrowser) {
  let currentMode = loadPreference(storageKeys.themeMode, 'auto', ['light', 'dark', 'auto']);
  applyTheme(currentMode);
  themeMode.subscribe((mode) => {
    currentMode = mode;
    applyTheme(mode);
  });
  mediaQuery?.addEventListener('change', () => {
    if (currentMode === 'auto') applyTheme(currentMode);
  });
}
