import { derived, writable } from 'svelte/store';

const storageKeys = {
  language: 'mothx.webui.language',
  themeMode: 'mothx.webui.themeMode'
};

const dictionaries = {
  zh: {
    'app.name': 'MothX',
    'app.local': '本地运行',
    'app.unknownPage': '未知的页面',
    'common.add': '添加',
    'common.clear': '清空',
    'common.close': '关闭',
    'common.completed': '完成',
    'common.connected': '已连接',
    'common.count': '{count} 个',
    'common.create': '创建',
    'common.delete': '删除',
    'common.disabled': '关闭',
    'common.disabledState': '已禁用',
    'common.disconnected': '未连接',
    'common.enable': '启用',
    'common.disable': '停用',
    'common.enabled': '开启',
    'common.failed': '失败',
    'common.idle': '空闲',
    'common.items': '共 {count} 项',
    'common.loading': '加载中...',
    'common.next': '下次 {time}',
    'common.no': '否',
    'common.open': '打开',
    'common.pending': '待处理',
    'common.refresh': '刷新',
    'common.remove': '移除',
    'common.running': '运行中',
    'common.save': '保存',
    'common.stop': '停止',
    'common.times': '{count} 次',
    'common.uninitialized': '未初始化',
    'common.yes': '是',
    'nav.newChat': '新对话',
    'nav.sessions': '历史对话',
    'nav.cron': '定时任务',
    'nav.channels': '通道',
    'nav.logs': '日志',
    'nav.settings': '设置',
    'sidebar.search': '搜索会话...',
    'sidebar.history': '历史对话',
    'sidebar.all': '全部',
    'sidebar.defaultSession': '默认会话',
    'sidebar.noHistory': '暂无历史',
    'sidebar.noMatches': '未匹配到会话',
    'channels.title': '消息通道',
    'channels.name': '名称',
    'channels.enabled': '启用',
    'channels.status': '状态',
    'channels.empty': '无通道',
    'logs.filter': '过滤日志内容',
    'logs.connect': '连接',
    'logs.disconnect': '断开',
    'logs.empty': '暂无日志',
    'sessions.deleted': '会话 {id} 已删除',
    'sessions.filter': '过滤会话（ID / 工作目录 / 标题）',
    'sessions.session': '会话',
    'sessions.workDir': '工作目录',
    'sessions.status': '状态',
    'sessions.messageCount': '消息数',
    'sessions.active': '运行中',
    'sessions.history': '历史',
    'sessions.empty': '没有可显示的会话',
    'cron.created': '已创建定时任务',
    'cron.deleted': '已删除任务 {id}',
    'cron.newTask': '新建任务',
    'cron.name': '名称',
    'cron.namePlaceholder': '每日总结',
    'cron.schedule': '调度表达式',
    'cron.schedulePlaceholder': '@daily 或 0 9 * * *',
    'cron.mode': '模式',
    'cron.oneshot': '一次性执行',
    'cron.promptPlaceholder': '要执行的指令...',
    'cron.list': '任务列表',
    'cron.empty': '暂无任务',
    'dirBrowser.title': '选择工作目录',
    'dirBrowser.up': '上级',
    'dirBrowser.loading': '加载中...',
    'dirBrowser.empty': '无子目录',
    'dirBrowser.cancel': '取消',
    'dirBrowser.select': '选择此目录',
    'prefs.language': '语言',
    'prefs.theme': '主题',
    'prefs.zh': '中',
    'prefs.en': 'EN',
    'prefs.light': '日间',
    'prefs.dark': '夜间',
    'prefs.auto': '自动',
    'prefs.preferences': '偏好设置',
    'topbar.chat.subtitle': 'AI 生成可能有误，请核实',
    'topbar.sessions.subtitle': '管理所有会话历史',
    'topbar.cron.subtitle': '调度自动运行的任务',
    'topbar.channels.subtitle': '外部消息通道状态',
    'topbar.logs.subtitle': '实时日志流',
    'topbar.settings.subtitle': 'Serve / App / Memory 配置',
    'topbar.openLogs': '开启日志',
    'topbar.closeLogs': '关闭日志',
    'topbar.refresh': '刷新',
    'settings.tabs.overview': '概览',
    'settings.tabs.serve': 'Serve 配置',
    'settings.tabs.workdir': '工作目录',
    'settings.tabs.app': '应用设置',
    'settings.tabs.memory': 'Memory',
    'settings.tabs.features': '功能开关',
    'settings.unknown': '未知的设置分组',
    'settings.overview.serve.desc': 'HTTP 监听、通道、WebUI 静态目录等运行时配置。',
    'settings.overview.app.desc': '模型、Provider、审批策略、上下文压缩等应用层参数。',
    'settings.overview.memory.desc': '长期记忆 memory.md 的启用与内容编辑。',
    'settings.overview.features.desc': '开关 API、WebSocket、Cron、Memory 等模块。',
    'settings.runtime.title': '运行时信息',
    'settings.runtime.version': '版本',
    'settings.runtime.listen': '监听',
    'settings.runtime.sessions': '会话总数',
    'settings.runtime.api': 'OpenAI API',
    'settings.features.hint': '只读展示。修改请在「Serve 配置」或「应用设置」中调整。',
    'settings.features.feature': '功能',
    'settings.features.status': '状态',
    'settings.features.description': '说明',
    'settings.features.api.label': 'OpenAI 兼容 API',
    'settings.features.api.desc': '开启后可通过 /v1/chat/completions 调用。',
    'settings.features.webUI.label': 'Web UI',
    'settings.features.webUI.desc': '当前界面本身，来自 Serve 静态资源目录。',
    'settings.features.websocket.label': 'WebSocket 日志',
    'settings.features.websocket.desc': '/ws/logs 实时日志推送。',
    'settings.features.cron.label': 'Cron 定时任务',
    'settings.features.cron.desc': '基于本地任务清单的调度器。',
    'settings.features.memory.label': 'Memory',
    'settings.features.memory.desc': 'memory.md 长期记忆。',
    'settings.features.multiAgent.label': '多 Agent',
    'settings.features.multiAgent.desc': '允许 spawn / send / destroy 子 Agent 工具。',
    'settings.memory.saved': 'Memory 已保存。',
    'settings.memory.notInitialized': '尚未初始化',
    'settings.app.saved': '应用设置已保存。',
    'settings.app.hint': '/api/settings - Providers / Approval / Context 等',
    'settings.serve.saved': 'Serve 配置已保存。监听或通道变更需要重启生效。',
    'settings.workdir.saved': '工作目录配置已保存。',
    'settings.workdir.title': '工作目录',
    'settings.workdir.mainHint': 'gateway.workingDir - Agent 的默认工作目录',
    'settings.workdir.default': '默认工作目录',
    'settings.workdir.defaultHint': 'Agent 执行命令时的默认 cwd。留空则使用进程当前目录。',
    'settings.workdir.allowed': '允许的工作目录',
    'settings.workdir.allowedHint': 'gateway.allowedWorkDirs - 安全白名单',
    'settings.workdir.noWhitelist': '未配置白名单。未配置时，Agent 可以切换到任意目录（仅受 sandbox 限制）。',
    'settings.workdir.arrayHint': '设为空数组 [] 表示禁止 Agent 覆盖工作目录。设为 null（删除整个字段）表示不限制。',
    'chat.suggestion.projectSummary': '阅读当前项目并总结核心模块和调用链',
    'chat.suggestion.reviewChanges': '审查最近的代码改动，列出潜在回归风险',
    'chat.suggestion.addTests': '帮我为这个 Go 包补充关键单元测试',
    'chat.suggestion.fixTests': '定位测试失败原因并给出最小修复方案',
    'chat.suggestion.refactor': '重构这段代码，保持行为不变并降低复杂度',
    'chat.suggestion.configAudit': '检查配置文件和启动参数是否存在冲突',
    'chat.suggestion.readme': '为新增功能整理一份简洁的 README 说明',
    'chat.suggestion.multiAgent': '生成一个安全的多 Agent 任务拆解方案',
    'chat.error.modelNoImages': '当前模型不支持图片输入',
    'chat.error.needWorkDir': '请先填写工作目录',
    'chat.error.unsupportedFileType': '不支持的文件类型：{name}',
    'chat.error.imageReadFailed': '读取图片失败：{name}',
    'chat.notice.stopped': '已停止请求。',
    'chat.welcome': '有什么我能帮你的吗？',
    'chat.you': '你',
    'chat.generating': '生成中',
    'chat.waitingModel': '正在等待模型响应...',
    'chat.plan': '任务计划',
    'chat.toolCall': '工具调用',
    'chat.toolEvents': '工具事件',
    'chat.sessionEvents': '会话事件',
    'chat.argsJson': '参数 JSON',
    'chat.loadingToolResult': '正在加载工具结果...',
    'chat.session': '会话',
    'chat.newSession': '新建会话',
    'chat.clearWorkDir': '清除',
    'chat.changeWorkDir': '更换目录',
    'chat.selectWorkDir': '选择工作目录',
    'chat.removeImage': '移除图片',
    'chat.apiDisabled': 'OpenAI API 已禁用',
    'chat.messagePlaceholder': '发消息...',
    'chat.uploadImage': '上传图片',
    'chat.selectModel': '选择模型',
    'chat.defaultModel': '默认模型',
    'chat.tools': '会话工具',
    'chat.toolToggle.webSearch': '为当前会话启用 webSearch',
    'chat.toolToggle.browser': '为当前会话启用 browser',
    'chat.toolToggle.a2aMaster': '为当前会话启用 a2aMaster',
    'chat.toolToggle.delegate': '为当前会话启用 delegate',
    'chat.toolToggle.multiAgent': '为当前会话启用 multi-agent',
    'chat.sending': '发送中',
    'chat.send': '发送',
    'chat.plan.done': '完成',
    'chat.plan.running': '进行中',
    'chat.plan.failed': '失败',
    'chat.plan.pending': '待处理',
    'chat.tool.result': '工具结果',
    'chat.tool.failed': '工具执行失败',
    'chat.tool.completed': '工具执行完成',
    'chat.tool.detailLoadFailed': '加载失败',
    'chat.tool.read.offset': '从第 {offset} 行',
    'chat.tool.read.limit': '最多 {limit} 行',
    'chat.tool.read.imageMode': '图片模式 {mode}',
    'chat.tool.read.maxLongEdge': '最长边 {value}px',
    'chat.tool.read.crop': '裁剪 {value}',
    'chat.tool.read.label': '读取文件',
    'chat.tool.read.missing': '(未指定文件)',
    'chat.tool.ls.label': '列出目录',
    'chat.tool.find.label': '查找文件',
    'chat.tool.find.missing': '(未指定 pattern)',
    'chat.tool.find.path': '目录 {path}',
    'chat.tool.find.maxDepth': '深度 {depth}',
    'chat.tool.find.maxResults': '最多 {count} 条',
    'chat.tool.find.pattern': '匹配模式',
    'chat.tool.find.searchPath': '搜索目录',
    'chat.tool.find.depth': '最大深度',
    'chat.tool.find.resultLimit': '结果上限',
    'chat.tool.grep.maxResults': '最多 {count} 条',
    'chat.tool.grep.label': '搜索文本',
    'chat.tool.grep.missing': '(未指定 pattern)',
    'chat.tool.bash.async': '后台运行',
    'chat.tool.bash.noTimeout': '无工具超时',
    'chat.tool.bash.timeout': '超时 {seconds}s',
    'chat.tool.bash.label': '执行命令',
    'chat.tool.bash.missing': '(未指定命令)',
    'chat.tool.edit.label': '编辑文件',
    'chat.tool.edit.missing': '(未指定文件)',
    'chat.tool.edit.oneEdit': '1 处替换',
    'chat.tool.edit.manyEdits': '{count} 处替换',
    'chat.tool.edit.editNumber': '替换 #{number}',
    'chat.tool.edit.lineChange': '{old} 行 -> {next} 行',
    'chat.tool.edit.oldText': '原文本',
    'chat.tool.edit.newText': '新文本',
    'chat.tool.edit.empty': '(空)',
    'chat.tool.write.label': '写入文件',
    'chat.tool.write.missing': '(未指定文件)',
    'chat.tool.write.lines': '{count} 行',
    'chat.tool.write.chars': '{count} 字符',
    'chat.tool.write.summary': '{lines} 行 / {chars} 字符',
    'chat.tool.write.preview': '写入预览',
    'chat.tool.write.content': '内容'
  },
  en: {
    'app.name': 'MothX',
    'app.local': 'Local runtime',
    'app.unknownPage': 'Unknown page',
    'common.add': 'Add',
    'common.clear': 'Clear',
    'common.close': 'Close',
    'common.completed': 'Completed',
    'common.connected': 'Connected',
    'common.count': '{count}',
    'common.create': 'Create',
    'common.delete': 'Delete',
    'common.disabled': 'Off',
    'common.disabledState': 'Disabled',
    'common.disconnected': 'Disconnected',
    'common.enable': 'Enable',
    'common.disable': 'Disable',
    'common.enabled': 'On',
    'common.failed': 'Failed',
    'common.idle': 'Idle',
    'common.items': '{count} items',
    'common.loading': 'Loading...',
    'common.next': 'Next {time}',
    'common.no': 'No',
    'common.open': 'Open',
    'common.pending': 'Pending',
    'common.refresh': 'Refresh',
    'common.remove': 'Remove',
    'common.running': 'Running',
    'common.save': 'Save',
    'common.stop': 'Stop',
    'common.times': '{count} runs',
    'common.uninitialized': 'Uninitialized',
    'common.yes': 'Yes',
    'nav.newChat': 'New Chat',
    'nav.sessions': 'Sessions',
    'nav.cron': 'Cron',
    'nav.channels': 'Channels',
    'nav.logs': 'Logs',
    'nav.settings': 'Settings',
    'sidebar.search': 'Search sessions...',
    'sidebar.history': 'Sessions',
    'sidebar.all': 'All',
    'sidebar.defaultSession': 'Default session',
    'sidebar.noHistory': 'No history',
    'sidebar.noMatches': 'No matching sessions',
    'channels.title': 'Message Channels',
    'channels.name': 'Name',
    'channels.enabled': 'Enabled',
    'channels.status': 'Status',
    'channels.empty': 'No channels',
    'logs.filter': 'Filter log content',
    'logs.connect': 'Connect',
    'logs.disconnect': 'Disconnect',
    'logs.empty': 'No logs',
    'sessions.deleted': 'Session {id} deleted',
    'sessions.filter': 'Filter sessions (ID / workdir / title)',
    'sessions.session': 'Session',
    'sessions.workDir': 'WorkDir',
    'sessions.status': 'Status',
    'sessions.messageCount': 'Messages',
    'sessions.active': 'Running',
    'sessions.history': 'History',
    'sessions.empty': 'No sessions to show',
    'cron.created': 'Cron task created',
    'cron.deleted': 'Task {id} deleted',
    'cron.newTask': 'New Task',
    'cron.name': 'Name',
    'cron.namePlaceholder': 'Daily summary',
    'cron.schedule': 'Schedule',
    'cron.schedulePlaceholder': '@daily or 0 9 * * *',
    'cron.mode': 'Mode',
    'cron.oneshot': 'One-shot',
    'cron.promptPlaceholder': 'Instruction to run...',
    'cron.list': 'Task List',
    'cron.empty': 'No tasks',
    'dirBrowser.title': 'Select WorkDir',
    'dirBrowser.up': 'Up',
    'dirBrowser.loading': 'Loading...',
    'dirBrowser.empty': 'No subdirectories',
    'dirBrowser.cancel': 'Cancel',
    'dirBrowser.select': 'Select This Directory',
    'prefs.language': 'Language',
    'prefs.theme': 'Theme',
    'prefs.zh': '中',
    'prefs.en': 'EN',
    'prefs.light': 'Light',
    'prefs.dark': 'Dark',
    'prefs.auto': 'Auto',
    'prefs.preferences': 'Preferences',
    'topbar.chat.subtitle': 'AI output may be wrong; verify important details',
    'topbar.sessions.subtitle': 'Manage all session history',
    'topbar.cron.subtitle': 'Schedule automated tasks',
    'topbar.channels.subtitle': 'External messaging channel status',
    'topbar.logs.subtitle': 'Live log stream',
    'topbar.settings.subtitle': 'Serve / App / Memory configuration',
    'topbar.openLogs': 'Open Logs',
    'topbar.closeLogs': 'Close Logs',
    'topbar.refresh': 'Refresh',
    'settings.tabs.overview': 'Overview',
    'settings.tabs.serve': 'Serve Config',
    'settings.tabs.workdir': 'WorkDirs',
    'settings.tabs.app': 'App Settings',
    'settings.tabs.memory': 'Memory',
    'settings.tabs.features': 'Features',
    'settings.unknown': 'Unknown settings group',
    'settings.overview.serve.desc': 'Runtime configuration for HTTP listening, channels, and the WebUI static directory.',
    'settings.overview.app.desc': 'Application settings for models, providers, approval policy, and context compaction.',
    'settings.overview.memory.desc': 'Enable and edit long-term memory in memory.md.',
    'settings.overview.features.desc': 'Toggle API, WebSocket, Cron, Memory, and related modules.',
    'settings.runtime.title': 'Runtime Info',
    'settings.runtime.version': 'Version',
    'settings.runtime.listen': 'Listen',
    'settings.runtime.sessions': 'Sessions',
    'settings.runtime.api': 'OpenAI API',
    'settings.features.hint': 'Read-only view. Change these in Serve Config or App Settings.',
    'settings.features.feature': 'Feature',
    'settings.features.status': 'Status',
    'settings.features.description': 'Description',
    'settings.features.api.label': 'OpenAI-compatible API',
    'settings.features.api.desc': 'Allows calls through /v1/chat/completions.',
    'settings.features.webUI.label': 'Web UI',
    'settings.features.webUI.desc': 'This interface, served from the Serve static asset directory.',
    'settings.features.websocket.label': 'WebSocket Logs',
    'settings.features.websocket.desc': 'Live log streaming through /ws/logs.',
    'settings.features.cron.label': 'Cron Tasks',
    'settings.features.cron.desc': 'Scheduler backed by the local task list.',
    'settings.features.memory.label': 'Memory',
    'settings.features.memory.desc': 'Long-term memory in memory.md.',
    'settings.features.multiAgent.label': 'Multi Agent',
    'settings.features.multiAgent.desc': 'Enables spawn / send / destroy sub-agent tools.',
    'settings.memory.saved': 'Memory saved.',
    'settings.memory.notInitialized': 'Not initialized',
    'settings.app.saved': 'App settings saved.',
    'settings.app.hint': '/api/settings - Providers / Approval / Context, etc.',
    'settings.serve.saved': 'Serve config saved. Listen or channel changes require restart.',
    'settings.workdir.saved': 'WorkDir config saved.',
    'settings.workdir.title': 'WorkDir',
    'settings.workdir.mainHint': 'gateway.workingDir - Default working directory for the agent',
    'settings.workdir.default': 'Default WorkDir',
    'settings.workdir.defaultHint': 'Default cwd for agent commands. Leave empty to use the process current directory.',
    'settings.workdir.allowed': 'Allowed WorkDirs',
    'settings.workdir.allowedHint': 'gateway.allowedWorkDirs - Security allowlist',
    'settings.workdir.noWhitelist': 'No allowlist configured. Without one, the agent may switch to any directory, constrained only by the sandbox.',
    'settings.workdir.arrayHint': 'Use an empty array [] to forbid agent workdir overrides. Use null by deleting the field to allow any directory.',
    'chat.suggestion.projectSummary': 'Read the current project and summarize core modules and call chains',
    'chat.suggestion.reviewChanges': 'Review recent code changes and list regression risks',
    'chat.suggestion.addTests': 'Add key unit tests for this Go package',
    'chat.suggestion.fixTests': 'Find why tests fail and propose the smallest fix',
    'chat.suggestion.refactor': 'Refactor this code while preserving behavior and reducing complexity',
    'chat.suggestion.configAudit': 'Check config files and launch args for conflicts',
    'chat.suggestion.readme': 'Write a concise README note for the new feature',
    'chat.suggestion.multiAgent': 'Create a safe multi-agent task breakdown',
    'chat.error.modelNoImages': 'The current model does not support image input',
    'chat.error.needWorkDir': 'Set a workdir first',
    'chat.error.unsupportedFileType': 'Unsupported file type: {name}',
    'chat.error.imageReadFailed': 'Failed to read image: {name}',
    'chat.notice.stopped': 'Request stopped.',
    'chat.welcome': 'What can I help with?',
    'chat.you': 'You',
    'chat.generating': 'Generating',
    'chat.waitingModel': 'Waiting for model response...',
    'chat.plan': 'Plan',
    'chat.toolCall': 'Tool Call',
    'chat.toolEvents': 'Tool Events',
    'chat.sessionEvents': 'Session Events',
    'chat.argsJson': 'Args JSON',
    'chat.loadingToolResult': 'Loading tool result...',
    'chat.session': 'Session',
    'chat.newSession': 'New Session',
    'chat.clearWorkDir': 'Clear',
    'chat.changeWorkDir': 'Change WorkDir',
    'chat.selectWorkDir': 'Select WorkDir',
    'chat.removeImage': 'Remove image',
    'chat.apiDisabled': 'OpenAI API is disabled',
    'chat.messagePlaceholder': 'Send a message...',
    'chat.uploadImage': 'Upload image',
    'chat.selectModel': 'Select model',
    'chat.defaultModel': 'Default model',
    'chat.tools': 'Session tools',
    'chat.toolToggle.webSearch': 'Enable webSearch for this session',
    'chat.toolToggle.browser': 'Enable browser for this session',
    'chat.toolToggle.a2aMaster': 'Enable a2aMaster for this session',
    'chat.toolToggle.delegate': 'Enable delegate for this session',
    'chat.toolToggle.multiAgent': 'Enable multi-agent for this session',
    'chat.sending': 'Sending',
    'chat.send': 'Send',
    'chat.plan.done': 'Done',
    'chat.plan.running': 'Running',
    'chat.plan.failed': 'Failed',
    'chat.plan.pending': 'Pending',
    'chat.tool.result': 'Tool result',
    'chat.tool.failed': 'Tool execution failed',
    'chat.tool.completed': 'Tool execution completed',
    'chat.tool.detailLoadFailed': 'Load failed',
    'chat.tool.read.offset': 'From line {offset}',
    'chat.tool.read.limit': 'Up to {limit} lines',
    'chat.tool.read.imageMode': 'Image mode {mode}',
    'chat.tool.read.maxLongEdge': 'Max long edge {value}px',
    'chat.tool.read.crop': 'Crop {value}',
    'chat.tool.read.label': 'Read File',
    'chat.tool.read.missing': '(file not specified)',
    'chat.tool.ls.label': 'List Directory',
    'chat.tool.find.label': 'Find Files',
    'chat.tool.find.missing': '(pattern not specified)',
    'chat.tool.find.path': 'Path {path}',
    'chat.tool.find.maxDepth': 'Depth {depth}',
    'chat.tool.find.maxResults': 'Up to {count} results',
    'chat.tool.find.pattern': 'Pattern',
    'chat.tool.find.searchPath': 'Search Path',
    'chat.tool.find.depth': 'Max Depth',
    'chat.tool.find.resultLimit': 'Result Limit',
    'chat.tool.grep.maxResults': 'Up to {count} results',
    'chat.tool.grep.label': 'Search Text',
    'chat.tool.grep.missing': '(pattern not specified)',
    'chat.tool.bash.async': 'Run in background',
    'chat.tool.bash.noTimeout': 'No tool timeout',
    'chat.tool.bash.timeout': 'Timeout {seconds}s',
    'chat.tool.bash.label': 'Run Command',
    'chat.tool.bash.missing': '(command not specified)',
    'chat.tool.edit.label': 'Edit File',
    'chat.tool.edit.missing': '(file not specified)',
    'chat.tool.edit.oneEdit': '1 replacement',
    'chat.tool.edit.manyEdits': '{count} replacements',
    'chat.tool.edit.editNumber': 'Replacement #{number}',
    'chat.tool.edit.lineChange': '{old} lines -> {next} lines',
    'chat.tool.edit.oldText': 'Old Text',
    'chat.tool.edit.newText': 'New Text',
    'chat.tool.edit.empty': '(empty)',
    'chat.tool.write.label': 'Write File',
    'chat.tool.write.missing': '(file not specified)',
    'chat.tool.write.lines': '{count} lines',
    'chat.tool.write.chars': '{count} chars',
    'chat.tool.write.summary': '{lines} lines / {chars} chars',
    'chat.tool.write.preview': 'Write Preview',
    'chat.tool.write.content': 'Content'
  }
};

const isBrowser = typeof window !== 'undefined';
const mediaQuery = isBrowser && typeof window.matchMedia === 'function'
  ? window.matchMedia('(prefers-color-scheme: dark)')
  : null;

function loadPreference(key, fallback, allowed) {
  if (!isBrowser) return fallback;
  const value = window.localStorage.getItem(key);
  return allowed.includes(value) ? value : fallback;
}

export const language = writable(loadPreference(storageKeys.language, 'zh', ['zh', 'en']));
export const themeMode = writable(loadPreference(storageKeys.themeMode, 'auto', ['light', 'dark', 'auto']));
export const effectiveTheme = writable(resolveEffectiveTheme(loadPreference(storageKeys.themeMode, 'auto', ['light', 'dark', 'auto'])));

export const t = derived(language, ($language) => {
  const dict = dictionaries[$language] || dictionaries.zh;
  return (key, params) => formatTemplate(dict[key] || dictionaries.zh[key] || key, params);
});

function formatTemplate(template, params) {
  if (!params || typeof params !== 'object') return template;
  return template.replace(/\{([a-zA-Z0-9_]+)\}/g, (match, key) => {
    const value = params[key];
    return value === undefined || value === null ? match : String(value);
  });
}

export function setLanguage(value) {
  if (!['zh', 'en'].includes(value)) return;
  language.set(value);
  if (isBrowser) window.localStorage.setItem(storageKeys.language, value);
}

export function setThemeMode(value) {
  if (!['light', 'dark', 'auto'].includes(value)) return;
  themeMode.set(value);
  if (isBrowser) window.localStorage.setItem(storageKeys.themeMode, value);
  applyTheme(value);
}

function resolveEffectiveTheme(mode) {
  if (mode === 'dark' || mode === 'light') return mode;
  return mediaQuery?.matches ? 'dark' : 'light';
}

function applyTheme(mode) {
  const theme = resolveEffectiveTheme(mode);
  effectiveTheme.set(theme);
  if (!isBrowser) return;
  document.documentElement.dataset.theme = theme;
  document.documentElement.dataset.themeMode = mode;
}

if (isBrowser) {
  let currentMode = loadPreference(storageKeys.themeMode, 'auto', ['light', 'dark', 'auto']);
  applyTheme(currentMode);
  themeMode.subscribe((mode) => {
    currentMode = mode;
    applyTheme(mode);
  });
  mediaQuery?.addEventListener('change', () => {
    if (currentMode === 'auto') applyTheme(currentMode);
  });
}
